<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
    <TargetFrameworks>net10.0;net10.0-android</TargetFrameworks>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('osx'))">$(TargetFrameworks);net10.0-ios</TargetFrameworks>
		<UseMaui>true</UseMaui>
		<UseMauiEssentials>true</UseMauiEssentials>
		<SingleProject>true</SingleProject>
		<PackageId>Nkraft.Mopups</PackageId>
    <RootNamespace>Nkraft.Mopups</RootNamespace>
		<Description>Fork of Mopups (LuckyDucko/Mopups) maintained for Android and iOS only</Description>
		<PackageProjectUrl>https://github.com/mr5z/Mopups</PackageProjectUrl>
    <RepositoryUrl>https://github.com/mr5z/Mopups</RepositoryUrl>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">24.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">12.2</SupportedOSPlatformVersion>
	</PropertyGroup>
  
	<PropertyGroup>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Authors>Mark L, Tyson Hooker, Maksym Koshovyi, Aswin P G, Kirill Lyubimov, Martijn Van Dijk, Shane Neuville</Authors>
		<Company>Nkraft</Company>
		<PackageTags>Nkraft.Mopups;Mopups;Popups;Maui;rg;Xamarin;ios;android;Dialogs</PackageTags>
		<Version>1.0.1</Version>
		<Title>Nkraft.Mopups (MAUI Popups)</Title>
		<PackageReleaseNotes>Mobile-only Mopups</PackageReleaseNotes>
		<IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>
  
	<ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.110" />
    <PackageReference Include="Microsoft.Maui.Essentials" Version="10.0.110" />
    <PackageReference Include="Nkraft.CrossUtility" Version="1.0.11.1" />
	</ItemGroup>
  
  <ItemGroup>
    <None Include="..\LICENSE" Pack="true" PackagePath="" />
    <None Include="..\README.md" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
